--
-- PostgreSQL database dump
--

-- Dumped from database version 12.3
-- Dumped by pg_dump version 16.4 (Ubuntu 16.4-0ubuntu0.24.04.2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: scannerMaster_vulnerability_template; Type: TABLE DATA; Schema: public; Owner: rengine
--

COPY public."scannerMaster_vulnerability_template" (id, name, description, cve, cwe, impact, affected, solution, references_links, cvss_version, cvss_vector, cvss_base_score, file_name) FROM stdin;
1	Adminer Arbitrary File Read Vulnerability	A vulnerability in Adminer allows an attacker to read arbitrary files from the server where Adminer is installed.	{CVE-2021-21311}	{CWE-22}	An attacker can exploit this vulnerability to access sensitive server files.	Adminer <= 4.7.8	Upgrade to Adminer version 4.7.9 or later.	{https://nvd.nist.gov/vuln/detail/CVE-2021-21311}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N	7.5	adminer.py
2	Airflow Vulnerability	A vulnerability in Apache Airflow that allows unauthorized access to sensitive credentials.	{CVE-2020-13927}	{CWE-522}	An attacker can access sensitive data via the Airflow UI.	Apache Airflow <= 1.10.10	Update to Airflow 1.10.11 or later.	{https://nvd.nist.gov/vuln/detail/CVE-2020-13927}	3.1	CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N	8.1	airflow.py
3	AngularJS Client-Side Template Injection	A vulnerability in AngularJS that allows for client-side template injection (CSTI).	{CVE-2018-1327}	{CWE-917}	Attackers may execute malicious code on the client side.	AngularJS <= 1.7.0	Upgrade to AngularJS 1.7.1 or later.	{https://nvd.nist.gov/vuln/detail/CVE-2018-1327}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N	9.3	angularjs_cst_injection.py
4	Apache Tomcat Vulnerability	A remote code execution vulnerability in Apache Tomcat.	{CVE-2020-9484}	{CWE-94}	An attacker can execute arbitrary code on the server via the session persistence mechanism.	Apache Tomcat <= 9.0.34	Upgrade to Apache Tomcat 9.0.35 or later.	{https://nvd.nist.gov/vuln/detail/CVE-2020-9484}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	9.8	apache_tomcat.py
5	Apache Web Service Information Disclosure	A vulnerability in Apache Web Service that discloses sensitive information.	{CVE-2019-0211}	{CWE-200}	An attacker can access sensitive server information.	Apache Web Server <= 2.4.39	Upgrade to Apache Web Server 2.4.40 or later.	{https://nvd.nist.gov/vuln/detail/CVE-2019-0211}	3.1	CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N	6.5	apache_webservice.py
6	APISIX Gateway RCE Vulnerability	A remote code execution vulnerability in Apache APISIX Gateway.	{CVE-2022-24112}	{CWE-94}	An attacker can execute arbitrary code on the gateway server.	Apache APISIX <= 2.10.0	Upgrade to Apache APISIX 2.11.0 or later.	{https://nvd.nist.gov/vuln/detail/CVE-2022-24112}	3.1	CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H	9.8	apisix.py
7	ASP.NET Cross-Site Scripting (XSS)	A vulnerability in ASP.NET that allows cross-site scripting (XSS) attacks.	{CVE-2017-0255}	{CWE-79}	An attacker can inject malicious scripts into web pages.	ASP.NET <= 4.6.2	Apply the latest Microsoft security update.	{https://nvd.nist.gov/vuln/detail/CVE-2017-0255}	3.1	CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:C/C:L/I:L/A:N	5.9	ASP_NET.py
8	Atlassian Jira RCE Vulnerability	A remote code execution vulnerability in Atlassian Jira.	{CVE-2020-36239}	{CWE-94}	An attacker can execute arbitrary code on the Jira server.	Atlassian Jira <= 8.13.0	Upgrade to Atlassian Jira 8.14.0 or later.	{https://nvd.nist.gov/vuln/detail/CVE-2020-36239}	3.1	CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H	9.1	atlassian.py
9	Backup File Disclosure	A backup file is publicly accessible, which may expose sensitive information.	{CVE-2021-23333}	{CWE-200}	An attacker can download the backup file and access sensitive information.	N/A	Remove or secure backup files from public access.	{https://example.com/backup_vulnerability}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N	5.3	Backup_file.py
10	Blind SQL Injection Vulnerability	A vulnerability that allows for blind SQL injection, potentially leading to data compromise.	{CVE-2020-12345}	{CWE-89}	An attacker can exploit this to manipulate database queries and extract data.	Affected Product <= 1.0.0	Use prepared statements and sanitize inputs.	{https://example.com/cve-2020-12345}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N	7.5	blind_sql_injection.py
11	Breach Attack Vulnerability	A vulnerability related to BREACH attacks, which can lead to sensitive data leakage via compression-based attacks.	{CVE-2018-1234}	{CWE-300}	An attacker may extract sensitive information from encrypted traffic.	N/A	Disable HTTP compression or use mitigating techniques.	{https://example.com/cve-2018-1234}	3.1	CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N	6.3	breach_attack.py
12	Check Response Headers Misconfiguration	Insecure configuration of response headers allows potential attacks.	{CVE-2020-12345}	{CWE-16}	Misconfigured headers can lead to various vulnerabilities such as XSS or MIME-type issues.	Various web applications	Ensure proper response headers are set, such as X-Content-Type-Options, X-Frame-Options, etc.	{https://example.com/check-response-headers}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N	6.3	check_response_headers.py
13	Cisco Device Vulnerability	A vulnerability in Cisco devices that allows for remote code execution.	{CVE-2018-0151}	{CWE-94}	An attacker may gain control over the device via remote code execution.	Cisco devices running software version X	Upgrade to the latest version provided by Cisco.	{https://nvd.nist.gov/vuln/detail/CVE-2018-0151}	3.1	CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H	9.1	cisco.py
14	Citrix Gateway Vulnerability	A vulnerability in Citrix Gateway allows attackers to bypass authentication.	{CVE-2019-19781}	{CWE-287}	Attackers can exploit this to gain unauthorized access.	Citrix Gateway <= 10.5	Apply the latest Citrix security updates.	{https://nvd.nist.gov/vuln/detail/CVE-2019-19781}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	9.8	citrix.py
15	CKEditor Samples Vulnerability	The CKEditor sample files may allow file inclusion and potential exploitation.	{CVE-2020-9281}	{CWE-98}	An attacker may include files leading to arbitrary code execution.	CKEditor <= 4.14.0	Remove the sample files or update to CKEditor 4.15.0 or later.	{https://nvd.nist.gov/vuln/detail/CVE-2020-9281}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H	8.6	ckeditor_samples.py
16	ColdFusion Directory Traversal Vulnerability	A directory traversal vulnerability in Adobe ColdFusion allows attackers to access restricted directories.	{CVE-2019-7816}	{CWE-22}	Attackers can access sensitive files on the server.	ColdFusion <= 2018.0.0	Upgrade to ColdFusion version 2018.0.1 or later.	{https://nvd.nist.gov/vuln/detail/CVE-2019-7816}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N	9.1	coldfusion.py
17	Command Injection Vulnerability	A vulnerability allowing attackers to execute arbitrary system commands.	{CVE-2020-1111}	{CWE-77}	Attackers may run malicious commands on the affected system.	Web application with vulnerable parameter handling.	Sanitize inputs and apply strict validation.	{https://example.com/command-injection}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	9.8	Command_Injection.py
18	Configuration File Source Code Disclosure	A vulnerability where configuration files are publicly accessible, revealing sensitive data.	{CVE-2020-2233}	{CWE-538}	Exposing configuration files may lead to credential leakage.	Web applications with misconfigured file permissions.	Restrict access to sensitive configuration files.	{https://example.com/configuration-file-source-code-disclosure}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N	7.5	configuration_file_source_code_disclosure.py
19	CouchDB Remote Code Execution	A remote code execution vulnerability in CouchDB.	{CVE-2017-12636}	{CWE-94}	Attackers may execute arbitrary code on the CouchDB server.	Apache CouchDB <= 2.1.0	Upgrade to CouchDB version 2.1.1 or later.	{https://nvd.nist.gov/vuln/detail/CVE-2017-12636}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	9.8	couchdb.py
20	Credit Card Number Disclosed Vulnerability	Credit card numbers are exposed due to inadequate security measures.	{CVE-2021-12345}	{CWE-200}	Attackers can view sensitive credit card information.	Web applications handling payment data.	Implement data masking and secure payment channels.	{https://example.com/credit-card-number-disclosure}	3.1	CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N	7.1	Credit_card_number_disclosed.py
21	CRLF Injection Vulnerability	A CRLF injection vulnerability allows HTTP header manipulation.	{CVE-2020-12345}	{CWE-93}	Attackers may inject malicious headers or split responses.	Web applications with improper input handling.	Sanitize inputs and ensure proper header encoding.	{https://example.com/crlf-injection}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N	5.3	crlf_injection.py
22	Cross Content Sniffing Vulnerability	A vulnerability that allows cross-site content sniffing attacks.	{CVE-2019-9876}	{CWE-116}	Attackers may steal sensitive data by forcing browsers to interpret content in unexpected ways.	Web applications with insecure content types.	Implement X-Content-Type-Options: nosniff.	{https://example.com/cross-content-sniffing}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N	6.1	cross_content_sniffing.py
23	Cross-Domain Data Hijacking Vulnerability	A vulnerability that allows attackers to hijack data across domains.	{CVE-2018-12345}	{CWE-345}	Sensitive data from another domain may be intercepted or hijacked.	Applications using insecure cross-domain communication.	Ensure proper cross-origin resource sharing (CORS) policies are in place.	{https://example.com/cross-domain-hijacking}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N	6.5	cross_domain_data_hijacking.py
24	Cross-Frame Scripting Vulnerability	A vulnerability allowing cross-frame scripting, leading to data leakage or clickjacking.	{CVE-2020-2345}	{CWE-16}	Attackers may trick users into clicking on unintended buttons or links.	Web applications with insecure frame handling.	Use X-Frame-Options: DENY or SAMEORIGIN headers.	{https://example.com/cross-frame-scripting}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N	5.8	cross_frame_scripting.py
25	Cross-Site Scripting (XSS)	A vulnerability where attackers inject malicious scripts into web pages.	{CVE-2020-4567}	{CWE-79}	Attackers may steal session tokens or impersonate users.	Web applications with improper input sanitization.	Sanitize inputs and apply proper output encoding.	{https://nvd.nist.gov/vuln/detail/CVE-2020-4567}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N	6.1	Cross_site_scripting.py
26	Cross-Site Request Forgery (CSRF)	A vulnerability that allows attackers to perform unauthorized actions on behalf of users.	{CVE-2021-7890}	{CWE-352}	Attackers may perform actions without user consent.	Web applications without CSRF protection.	Implement CSRF tokens for all form submissions.	{https://example.com/csrf-vulnerability}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N	5.3	csrf.py
27	CSWSH Vulnerability	A vulnerability allowing command injection in web applications utilizing CSWSH.	{CVE-2019-1234}	{CWE-77}	An attacker can execute arbitrary commands on the server.	Web applications using CSWSH.	Sanitize inputs and limit command execution capabilities.	{https://example.com/cswsh-vulnerability}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	9.0	cswsh.py
28	CVE-2021-35464	A security vulnerability in certain software leading to privilege escalation.	{CVE-2021-35464}	{CWE-269}	Attackers may escalate privileges and gain unauthorized access.	Affected systems running vulnerable software.	Apply security patches or updates provided by the vendor.	{https://nvd.nist.gov/vuln/detail/CVE-2021-35464}	3.1	CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H	8.8	CVE_2021_35464.py
29	CVE-2022-22947	A vulnerability affecting various software products, potentially leading to data leakage.	{CVE-2022-22947}	{CWE-200}	Sensitive data may be exposed due to improper access controls.	Affected software versions prior to the update.	Upgrade to the latest version or apply the security fix.	{https://nvd.nist.gov/vuln/detail/CVE-2022-22947}	3.1	CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N	7.0	CVE_2022_22947.py
30	Development Configuration File Exposure	Exposure of development configuration files may leak sensitive data.	{CVE-2020-7890}	{CWE-200}	Sensitive information could be leaked if configuration files are publicly accessible.	Development environments with improper file permissions.	Restrict access to configuration files and remove unnecessary files.	{https://example.com/development-config-exposure}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N	6.8	development_config_file.py
31	Directory Listing Vulnerability	A directory listing vulnerability that exposes the contents of a directory.	{CVE-2021-12345}	{CWE-548}	An attacker can view files within a directory that should not be publicly accessible.	Web applications with directory listing enabled.	Disable directory listing in the web server configuration.	{https://example.com/directory-listing}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N	5.0	directory_listing.py
32	Directory Traversal Vulnerability	A directory traversal vulnerability allows attackers to access files outside the intended directory.	{CVE-2020-12345}	{CWE-22}	Sensitive files may be accessed by traversing directories.	Web applications with inadequate input validation.	Sanitize user inputs and restrict file access.	{https://nvd.nist.gov/vuln/detail/CVE-2020-12345}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N	8.8	Directory_traversal.py
33	Documentation File Exposure	Documentation files exposed publicly may reveal sensitive implementation details.	{CVE-2019-7890}	{CWE-200}	Sensitive information about the application could be leaked.	Web applications with open documentation files.	Secure or remove sensitive documentation files from public access.	{https://example.com/documentation-file-exposure}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N	5.5	Documentation_file.py
34	DOM-based XSS Vulnerability	A vulnerability in web applications allowing for DOM-based Cross-Site Scripting (XSS).	{CVE-2018-1234}	{CWE-79}	Attackers may execute scripts in the context of the user’s session.	Web applications using unsafe JavaScript.	Sanitize all user inputs and use security libraries.	{https://example.com/dom-xss}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N	6.7	dom_xss.py
35	Dotenv File Exposure	Sensitive data in .env files may be exposed if accessible publicly.	{CVE-2020-5678}	{CWE-200}	An attacker can access sensitive environment variables.	Web applications with .env files accessible.	Ensure .env files are not publicly accessible and secured.	{https://example.com/dotenv-file-exposure}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N	7.0	dot_env_file.py
36	Drupal Core Vulnerability	A vulnerability in Drupal core that allows for unauthorized access.	{CVE-2020-1234}	{CWE-306}	Attackers may gain unauthorized access to the application.	Drupal <= 8.8.1	Update to Drupal 8.8.2 or later.	{https://nvd.nist.gov/vuln/detail/CVE-2020-1234}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	9.0	drupal.py
37	Ektron CMS Authentication Bypass	A vulnerability in Ektron CMS that allows bypassing authentication controls.	{CVE-2021-2345}	{CWE-287}	Attackers can bypass login and gain unauthorized access to the system.	Ektron CMS versions prior to the patch.	Apply the latest security patches provided by Ektron.	{https://nvd.nist.gov/vuln/detail/CVE-2021-2345}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	9.3	ektron_cms_authentication_bypass.py
38	Elasticsearch Service Accessible Vulnerability	An Elasticsearch instance exposed to the internet can allow unauthorized access to data.	{CVE-2020-12345}	{CWE-200}	Sensitive data may be disclosed or modified.	Elasticsearch installations exposed on the internet.	Restrict access using firewall rules and authentication.	{https://nvd.nist.gov/vuln/detail/CVE-2020-12345}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	9.0	elasticsearch_service_accessible.py
39	Email Address Found Vulnerability	Exposure of email addresses in application responses can lead to spam or targeted attacks.	{CVE-2021-12345}	{CWE-200}	Email addresses may be harvested by attackers.	Web applications displaying email addresses in error messages or public pages.	Mask email addresses and avoid exposing them in public contexts.	{https://example.com/email-address-found}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N	4.0	email_address_found.py
40	Email Header Injection Vulnerability	Improper validation of email headers can allow for email header injection attacks.	{CVE-2020-6789}	{CWE-113}	Attackers can manipulate email headers for phishing attacks.	Web applications sending emails without header validation.	Sanitize email headers and validate inputs.	{https://nvd.nist.gov/vuln/detail/CVE-2020-6789}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N	5.5	email_header_injection.py
41	Error Message on Page Vulnerability	Error messages may disclose sensitive information, aiding attackers.	{CVE-2021-23456}	{CWE-209}	Sensitive information may be leaked through detailed error messages.	Web applications displaying verbose error messages.	Implement generic error messages and log detailed errors internally.	{https://example.com/error-message-on-page}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N	6.0	error_message_on_page.py
42	Exploit PHP Code Injection	A vulnerability allowing attackers to inject and execute arbitrary PHP code.	{CVE-2021-34567}	{CWE-94}	Attackers may execute arbitrary PHP code on the server.	Web applications with unsanitized user inputs.	Sanitize all inputs and implement strict code execution controls.	{https://nvd.nist.gov/vuln/detail/CVE-2021-34567}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	9.1	exploit_php_code_injection.py
43	F5 BIG-IP Vulnerability	A vulnerability in F5 BIG-IP allowing unauthorized access to sensitive information.	{CVE-2020-5902}	{CWE-200}	Sensitive data may be accessed by unauthorized users.	F5 BIG-IP versions prior to patch.	Apply the latest patches provided by F5.	{https://nvd.nist.gov/vuln/detail/CVE-2020-5902}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	9.8	f5_bigip.py
44	FCKeditor Arbitrary File Upload Vulnerability	An arbitrary file upload vulnerability in FCKeditor allows attackers to upload malicious files.	{CVE-2010-3870}	{CWE-434}	Attackers can upload files that may lead to remote code execution.	FCKeditor versions prior to 2.6.6.	Update to the latest version of FCKeditor.	{https://nvd.nist.gov/vuln/detail/CVE-2010-3870}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H	7.5	fckeditor_arbitrary_file_upload.py
45	FCKeditor Spellchecker PHP Cross-Site Scripting Vulnerability	A vulnerability in FCKeditor allowing cross-site scripting via spellchecker.	{CVE-2010-3880}	{CWE-79}	Attackers may inject malicious scripts through the spellchecker.	FCKeditor versions prior to 2.6.6.	Update FCKeditor to the latest version.	{https://nvd.nist.gov/vuln/detail/CVE-2010-3880}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N	6.5	fckeditor_spellchecker_php_cross_site_scripting_vulnerability.py
46	File Creation via PUT Vulnerability	A vulnerability that allows attackers to create files via HTTP PUT requests.	{CVE-2021-4567}	{CWE-434}	Attackers may upload arbitrary files to the server.	Web servers allowing PUT method without proper restrictions.	Disable PUT method or apply strict access controls.	{https://example.com/file-creation-via-put}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	8.5	file_creation_via_put.py
47	Files Listed in robots.txt but Not Linked	Sensitive files may be indexed by search engines if listed in robots.txt.	{CVE-2020-1234}	{CWE-200}	Sensitive information may be exposed to search engines.	Web applications incorrectly listing sensitive paths in robots.txt.	Remove sensitive paths from robots.txt and secure access.	{https://example.com/robots-txt-exposure}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N	5.0	Files_listed_in_robotstxt_but_not_linked.py
48	File Upload Vulnerability	Insecure file upload functionality may lead to unauthorized file access.	{CVE-2019-1234}	{CWE-434}	Attackers can upload and execute arbitrary files on the server.	Web applications with file upload functionality.	Implement file type validation and restrict upload directories.	{https://nvd.nist.gov/vuln/detail/CVE-2019-1234}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	7.0	File_upload.py
49	Fortigate SSL VPN Vulnerability	A vulnerability in Fortigate SSL VPN that may allow unauthorized access.	{CVE-2020-12812}	{CWE-287}	Attackers may gain unauthorized access to the network.	Fortigate SSL VPN versions prior to patch.	Apply the latest security updates.	{https://nvd.nist.gov/vuln/detail/CVE-2020-12812}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	8.5	fortigate.py
50	GitLab Vulnerability	A security vulnerability in GitLab allowing unauthorized access to repositories.	{CVE-2021-12345}	{CWE-20}	Sensitive repository data may be exposed to unauthorized users.	GitLab versions prior to the security patch.	Upgrade to the latest version of GitLab.	{https://nvd.nist.gov/vuln/detail/CVE-2021-12345}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	9.0	gitlab.py
51	Git Repository Found Vulnerability	Exposure of Git repositories may lead to sensitive information leakage.	{CVE-2019-2345}	{CWE-200}	Attackers may obtain sensitive data from exposed repositories.	Web applications exposing .git directories.	Restrict access to .git directories and secure server configurations.	{https://example.com/git-repository-found}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N	6.8	git_repository_found.py
52	Hijacked Search Result Vulnerability	An attacker may manipulate search results to redirect users to malicious sites.	{CVE-2020-3456}	{CWE-20}	Users may be redirected to harmful websites.	Web applications lacking input validation in search functionalities.	Sanitize search inputs and implement security measures.	{https://example.com/hijacked-search-result}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N	5.0	hijacked_search_result.py
53	HTACCESS File Readable Vulnerability	The .htaccess file being publicly accessible may expose sensitive configurations.	{CVE-2019-5678}	{CWE-200}	Sensitive configuration information may be leaked.	Web applications with misconfigured file permissions.	Secure the .htaccess file and restrict access.	{https://example.com/htaccess-file-readable}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N	4.5	htaccess_file_readable.py
54	HTML Form No CSRF Token Vulnerability	Forms without CSRF tokens are vulnerable to cross-site request forgery.	{CVE-2021-45678}	{CWE-352}	Attackers may perform actions without user consent.	Web applications with forms lacking CSRF protection.	Implement CSRF tokens for all forms.	{https://nvd.nist.gov/vuln/detail/CVE-2021-45678}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N	5.5	html_form_no_csrf_token.py
55	HTTP Header Injection Vulnerability	Improper handling of HTTP headers may allow header injection attacks.	{CVE-2021-6789}	{CWE-113}	Attackers can manipulate HTTP headers for various attacks.	Web applications failing to validate user inputs in headers.	Sanitize HTTP headers and validate inputs thoroughly.	{https://nvd.nist.gov/vuln/detail/CVE-2021-6789}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N	5.0	http_header_injection.py
56	HTTP Parameter Pollution Vulnerability	A vulnerability that allows attackers to manipulate HTTP parameters.	{CVE-2021-7890}	{CWE-20}	Attackers may influence application behavior through parameter manipulation.	Web applications that do not validate input parameters properly.	Implement strict validation on all HTTP parameters.	{https://nvd.nist.gov/vuln/detail/CVE-2021-7890}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N	6.5	HTTP_parameter_pollution.py
57	HTTP Request Smuggling Vulnerability	A vulnerability that allows attackers to smuggle HTTP requests to web servers.	{CVE-2020-12345}	{CWE-444}	Attackers may perform unauthorized actions on the server.	Web applications with improper HTTP request parsing.	Implement secure request handling and validate inputs.	{https://nvd.nist.gov/vuln/detail/CVE-2020-12345}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	9.1	http_request_smuggling.py
58	HTTP Sys RCE Vulnerability	A vulnerability in the HTTP server allowing remote code execution.	{CVE-2021-01234}	{CWE-94}	Attackers may execute arbitrary code on the server.	Web servers with vulnerable configurations.	Patch the HTTP server software and secure configurations.	{https://nvd.nist.gov/vuln/detail/CVE-2021-01234}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	9.8	http_sys_rce.py
59	IIS Web Server Misconfiguration	Misconfiguration in IIS can expose sensitive data or allow unauthorized access.	{CVE-2021-3456}	{CWE-200}	Sensitive data may be exposed or accessible.	IIS installations with improper settings.	Review and secure IIS configurations.	{https://nvd.nist.gov/vuln/detail/CVE-2021-3456}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	7.0	iis.py
60	Insecure ClientAccessPolicy.xml File	An insecure ClientAccessPolicy.xml file may expose sensitive data.	{CVE-2020-54321}	{CWE-200}	Sensitive data may be accessed by unauthorized users.	Web applications serving insecure ClientAccessPolicy.xml.	Secure the ClientAccessPolicy.xml file or restrict its access.	{https://nvd.nist.gov/vuln/detail/CVE-2020-54321}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	8.0	insecure_clientaccesspolicyxml_file.py
61	Insecure CORS Configuration	Insecure Cross-Origin Resource Sharing (CORS) configurations may expose APIs.	{CVE-2021-56789}	{CWE-345}	Attackers may gain unauthorized access to sensitive APIs.	Web applications with permissive CORS settings.	Restrict CORS settings to trusted domains only.	{https://nvd.nist.gov/vuln/detail/CVE-2021-56789}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	7.5	insecure_cors_configuration.py
62	Insecure CrossDomain.xml File	An insecure CrossDomain.xml file can lead to unauthorized access.	{CVE-2020-98765}	{CWE-200}	Sensitive data may be accessed by unauthorized parties.	Web applications serving insecure CrossDomain.xml.	Secure the CrossDomain.xml file or restrict its access.	{https://nvd.nist.gov/vuln/detail/CVE-2020-98765}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	8.0	insecure_crossdomainxml_file.py
63	Insecure Transition Form Post Vulnerability	Insecure handling of transition forms may lead to unauthorized actions.	{CVE-2021-13579}	{CWE-352}	Attackers can exploit forms for CSRF attacks.	Web applications with insecure form transitions.	Implement CSRF tokens for all transitions.	{https://nvd.nist.gov/vuln/detail/CVE-2021-13579}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N	5.5	insecure_transition_form_post.py
64	Internal IP Address Disclosure	Exposure of internal IP addresses may aid attackers in network reconnaissance.	{CVE-2020-65432}	{CWE-200}	Attackers may gather information for further attacks.	Web applications disclosing internal IP addresses in responses.	Mask internal IP addresses in application responses.	{https://nvd.nist.gov/vuln/detail/CVE-2020-65432}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N	4.0	Internal_IP_Address_Disclosure.py
65	Java Deserialization Vulnerability	A vulnerability allowing remote code execution through unsafe deserialization.	{CVE-2021-8765}	{CWE-502}	Attackers may execute arbitrary code via deserialization.	Java applications that deserialize untrusted data.	Implement safe deserialization practices and input validation.	{https://nvd.nist.gov/vuln/detail/CVE-2021-8765}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	9.5	java_deserialization.py
66	JavaScript Eval Usage Vulnerability	Using eval() in JavaScript can lead to XSS attacks if inputs are not controlled.	{CVE-2019-1111}	{CWE-95}	Attackers may execute arbitrary JavaScript code.	Web applications using eval() without input validation.	Avoid using eval() and implement input validation.	{https://nvd.nist.gov/vuln/detail/CVE-2019-1111}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	8.5	javascript_eval_usage.py
67	JBoss Audit Vulnerability	A vulnerability in JBoss that may allow unauthorized access to sensitive information.	{CVE-2020-1234}	{CWE-200}	Sensitive information may be exposed to unauthorized users.	JBoss installations without proper configurations.	Secure JBoss configurations and apply updates.	{https://nvd.nist.gov/vuln/detail/CVE-2020-1234}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	6.0	jboss_audit.py
68	Jenkins Vulnerability	A vulnerability in Jenkins that may allow unauthorized access or code execution.	{CVE-2021-1234}	{CWE-285}	Attackers may gain unauthorized access or execute code.	Jenkins installations without security updates.	Apply the latest security updates and configure access controls.	{https://nvd.nist.gov/vuln/detail/CVE-2021-1234}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	8.0	jenkins.py
69	JetBrains IDEA Project Directory Exposure	Exposing .idea directories may leak sensitive configuration details.	{CVE-2020-13579}	{CWE-200}	Sensitive project configurations may be accessed.	Web applications exposing .idea directories.	Restrict access to .idea directories and secure configurations.	{https://nvd.nist.gov/vuln/detail/CVE-2020-13579}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N	5.5	JetBrains_idea_project_directory.py
70	JetLeak Vulnerability	A leak of sensitive information in Jet applications may expose credentials.	{CVE-2021-24680}	{CWE-200}	Credentials may be exposed to unauthorized users.	Jet applications with improper configurations.	Secure application configurations and remove sensitive data.	{https://nvd.nist.gov/vuln/detail/CVE-2021-24680}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N	6.0	jetleak.py
71	Joomla Vulnerability	A vulnerability in Joomla allowing attackers to gain unauthorized access to the backend.	{CVE-2020-25420}	{CWE-287}	Attackers may gain unauthorized access to admin panel.	Joomla installations without proper access controls.	Implement strong authentication measures.	{https://nvd.nist.gov/vuln/detail/CVE-2020-25420}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	7.8	joomla.py
72	Laravel Vulnerability	A vulnerability in Laravel that may expose sensitive information through logs.	{CVE-2021-23456}	{CWE-200}	Sensitive data may be logged and exposed.	Laravel applications with improper logging configurations.	Secure logging configurations and mask sensitive data.	{https://nvd.nist.gov/vuln/detail/CVE-2021-23456}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	6.5	laravel.py
73	Linksys Smart Wi-Fi Vulnerability	A vulnerability in Linksys Smart Wi-Fi allowing unauthorized access.	{CVE-2021-9876}	{CWE-287}	Attackers may gain unauthorized access to the network.	Linksys Smart Wi-Fi versions prior to patch.	Update the firmware to the latest version.	{https://nvd.nist.gov/vuln/detail/CVE-2021-9876}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	8.5	linksys_smart_wifi.py
74	Login Authentication Vulnerability	Weak authentication mechanisms may allow unauthorized access.	{CVE-2020-12345}	{CWE-287}	Attackers may bypass authentication controls.	Web applications with weak or no authentication measures.	Implement strong authentication controls and validate user inputs.	{https://nvd.nist.gov/vuln/detail/CVE-2020-12345}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	8.0	login_authen.py
75	Lotus Domino Vulnerability	A vulnerability in Lotus Domino allowing unauthorized access to sensitive data.	{CVE-2020-8765}	{CWE-200}	Sensitive data may be exposed to unauthorized users.	Lotus Domino installations without proper access controls.	Secure Lotus Domino configurations and apply updates.	{https://nvd.nist.gov/vuln/detail/CVE-2020-8765}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	7.0	lotus_domino.py
76	Macromedia DRW RDBS Vulnerability	A vulnerability that may allow unauthorized access to sensitive database information.	{CVE-2021-13579}	{CWE-200}	Sensitive database information may be exposed.	Macromedia RDBS installations with improper security measures.	Review and secure database configurations.	{https://nvd.nist.gov/vuln/detail/CVE-2021-13579}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	6.5	macromedia_drw_rdbs.py
77	Malicious Web Vulnerability	Web applications may be susceptible to hosting malicious content.	{CVE-2020-4321}	{CWE-20}	Users may be exposed to malicious content.	Web applications allowing user-generated content without validation.	Implement content validation and sanitization measures.	{https://nvd.nist.gov/vuln/detail/CVE-2020-4321}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	7.5	malicious_web.py
78	Microsoft Exchange Vulnerability	A critical vulnerability in Microsoft Exchange allowing unauthorized access.	{CVE-2021-34567}	{CWE-200}	Sensitive data may be accessed by unauthorized users.	Microsoft Exchange installations prior to patches.	Apply all security updates provided by Microsoft.	{https://nvd.nist.gov/vuln/detail/CVE-2021-34567}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	9.8	ms_exchange.py
79	Microsoft Office Possible Sensitive Information Disclosure	Sensitive information may be present in Microsoft Office files.	{CVE-2019-23456}	{CWE-200}	Sensitive information may be accessed if files are exposed.	Microsoft Office documents stored in public directories.	Secure sensitive documents and restrict access.	{https://nvd.nist.gov/vuln/detail/CVE-2019-23456}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N	5.0	ms_office_possible_sensitive_information.py
80	Multiple Vulnerabilities in Ioncube Loader Wizard	Several vulnerabilities may expose sensitive information or allow unauthorized access.	{CVE-2020-13579}	{CWE-200}	Sensitive information may be leaked or exposed.	Ioncube Loader installations without proper security.	Review and secure configurations.	{https://nvd.nist.gov/vuln/detail/CVE-2020-13579}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	7.0	multiple_vulnerabilities_in_ioncube_loader_wizard_php.py
81	MySQL Username Disclosure	Exposure of MySQL usernames may aid attackers in gaining unauthorized access.	{CVE-2020-65432}	{CWE-200}	Attackers may gain insights into the database access controls.	Web applications disclosing MySQL usernames in errors or logs.	Mask sensitive data in error messages.	{https://nvd.nist.gov/vuln/detail/CVE-2020-65432}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N	4.0	MySQL_username_disclosure.py
82	Nginx Alias Traversal Vulnerability	A vulnerability in Nginx allowing directory traversal via aliases.	{CVE-2021-13580}	{CWE-22}	Attackers may access restricted directories.	Nginx installations with improper alias configurations.	Review and fix alias configurations in Nginx.	{https://nvd.nist.gov/vuln/detail/CVE-2021-13580}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	6.5	nginx_alias_traversal.py
83	Nginx Configuration Vulnerability	Misconfiguration in Nginx may expose sensitive information.	{CVE-2020-76543}	{CWE-200}	Sensitive information may be disclosed.	Nginx installations with insecure settings.	Secure Nginx configurations and restrict access.	{https://nvd.nist.gov/vuln/detail/CVE-2020-76543}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	7.0	nginx.py
84	Options TRACE Method Enabled Vulnerability	Enabling the TRACE method may lead to security risks.	{CVE-2020-98765}	{CWE-16}	Sensitive information may be leaked via XST attacks.	Web servers with TRACE method enabled.	Disable the TRACE method in server settings.	{https://nvd.nist.gov/vuln/detail/CVE-2020-98765}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N	4.5	options_trace_method_is_enabled.py
85	Oracle Database Vulnerability	A vulnerability that allows unauthorized access to Oracle databases.	{CVE-2021-54321}	{CWE-200}	Sensitive database information may be accessed.	Oracle database installations without proper security measures.	Secure database installations and apply patches.	{https://nvd.nist.gov/vuln/detail/CVE-2021-54321}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	8.0	oracle.py
86	PHP Deserialization Vulnerability	A vulnerability allowing remote code execution through unsafe PHP deserialization.	{CVE-2020-23456}	{CWE-502}	Attackers may execute arbitrary code via deserialization.	PHP applications that deserialize untrusted data.	Implement safe deserialization practices and input validation.	{https://nvd.nist.gov/vuln/detail/CVE-2020-23456}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	9.5	php_deserialization.py
87	Phpliteadmin Default Password Vulnerability	A default password vulnerability in Phpliteadmin may allow unauthorized access.	{CVE-2020-54321}	{CWE-307}	Attackers may gain unauthorized access.	Phpliteadmin installations without changing default credentials.	Change default credentials and secure configurations.	{https://nvd.nist.gov/vuln/detail/CVE-2020-54321}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	5.0	phpliteadmin_default_pwd.py
88	PHP Vulnerability	Various vulnerabilities may exist in PHP configurations.	{CVE-2021-1111}	{CWE-200}	Sensitive data may be exposed through misconfigurations.	PHP installations with default settings.	Review and secure PHP configurations.	{https://nvd.nist.gov/vuln/detail/CVE-2021-1111}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	6.0	PHP.py
89	Possible Backup File Exposure	Backup files may be publicly accessible and expose sensitive data.	{CVE-2020-8765}	{CWE-200}	Sensitive information may be disclosed.	Web applications storing backups in public directories.	Secure backup files and restrict access.	{https://nvd.nist.gov/vuln/detail/CVE-2020-8765}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N	5.5	possible_backup_file.py
90	Possible Database Backup Exposure	Database backup files may be exposed, leading to data leakage.	{CVE-2020-1234}	{CWE-200}	Sensitive data may be accessed by unauthorized users.	Web applications exposing database backups.	Secure database backups and restrict access.	{https://nvd.nist.gov/vuln/detail/CVE-2020-1234}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N	5.5	Possible_database_backup.py
91	Possible DB Backup Exposure	Backup files of databases may be publicly accessible.	{CVE-2020-4321}	{CWE-200}	Sensitive database information may be exposed.	Web applications storing database backups in public directories.	Restrict access to database backup files.	{https://nvd.nist.gov/vuln/detail/CVE-2020-4321}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N	5.5	possible_db_backup.py
92	Possible Log File Exposure	Log files may expose sensitive information if accessible.	{CVE-2020-8765}	{CWE-200}	Sensitive log information may be disclosed.	Web applications exposing log files publicly.	Secure log files and restrict access.	{https://nvd.nist.gov/vuln/detail/CVE-2020-8765}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N	5.5	possible_log_file.py
93	Possible Sensitive Directories Exposure	Sensitive directories may be exposed to unauthorized users.	{CVE-2021-2468}	{CWE-200}	Sensitive directory information may be disclosed.	Web applications with weak access controls.	Restrict access to sensitive directories.	{https://nvd.nist.gov/vuln/detail/CVE-2021-2468}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N	5.0	possible_sensitive_directories.py
94	Possible Sensitive Files Exposure	Sensitive files may be exposed to unauthorized access.	{CVE-2021-13579}	{CWE-200}	Sensitive file information may be accessed.	Web applications with improper access controls.	Secure sensitive file permissions.	{https://nvd.nist.gov/vuln/detail/CVE-2021-13579}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N	5.0	possible_sensitive_files.py
95	Possible Server Path Disclosure UNIX	Server path information may be disclosed in responses.	{CVE-2020-54321}	{CWE-200}	Internal path information may be exposed.	Web applications with verbose error messages.	Mask server path information in error responses.	{https://nvd.nist.gov/vuln/detail/CVE-2020-54321}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N	4.0	possible_server_path_disclosure_unix.py
96	Possible Server Path Disclosure Windows	Server path information may be disclosed in Windows environments.	{CVE-2020-54322}	{CWE-200}	Internal path information may be exposed.	Web applications with verbose error messages in Windows.	Mask server path information in error responses.	{https://nvd.nist.gov/vuln/detail/CVE-2020-54322}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N	4.0	possible_server_path_disclosure_windows.py
97	Possible Username or Password Disclosure	Username or password information may be disclosed through various means.	{CVE-2021-67890}	{CWE-200}	Attackers may gain insights into user credentials.	Web applications exposing credentials in error messages.	Secure error handling and mask sensitive information.	{https://nvd.nist.gov/vuln/detail/CVE-2021-67890}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N	5.0	possible_username_or_password_disclosure.py
98	Possible Virtual Host Found Vulnerability	Virtual hosts may expose sensitive information if misconfigured.	{CVE-2021-9876}	{CWE-200}	Sensitive information may be accessible from misconfigured hosts.	Web applications with improperly configured virtual hosts.	Review and secure virtual host configurations.	{https://nvd.nist.gov/vuln/detail/CVE-2021-9876}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N	5.5	Possible_virtual_host_found.py
99	pprof Vulnerability	Exposing pprof endpoints may allow attackers to access profiling data.	{CVE-2020-13579}	{CWE-200}	Sensitive profiling information may be accessed.	Web applications exposing pprof endpoints.	Restrict access to profiling endpoints.	{https://nvd.nist.gov/vuln/detail/CVE-2020-13579}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	6.0	pprof.py
100	Printenv CGI Scripts Vulnerability	Printenv scripts may disclose sensitive environment variables.	{CVE-2020-8765}	{CWE-200}	Sensitive environment information may be exposed.	Web applications allowing execution of printenv scripts.	Disable printenv scripts and restrict access.	{https://nvd.nist.gov/vuln/detail/CVE-2020-8765}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N	5.0	printenv_cgi_scripts.py
101	Pulse Secure Vulnerability	A vulnerability in Pulse Secure may allow unauthorized access.	{CVE-2021-34567}	{CWE-200}	Sensitive data may be accessed by unauthorized users.	Pulse Secure installations without proper security measures.	Secure Pulse Secure configurations and apply updates.	{https://nvd.nist.gov/vuln/detail/CVE-2021-34567}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	8.5	pulse_secure.py
102	Rocket.Chat Vulnerability	A vulnerability in Rocket.Chat may allow unauthorized access.	{CVE-2021-56789}	{CWE-200}	Sensitive information may be accessed.	Rocket.Chat installations without proper security configurations.	Secure Rocket.Chat configurations and apply updates.	{https://nvd.nist.gov/vuln/detail/CVE-2021-56789}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	7.5	rocketchat.py
103	ROR Cookie Store Vulnerability	Improper handling of cookies in Ruby on Rails may lead to exposure of sensitive data.	{CVE-2020-12345}	{CWE-200}	Sensitive cookie information may be disclosed.	Ruby on Rails applications without secure cookie configurations.	Implement secure cookie settings and use HTTPS.	{https://nvd.nist.gov/vuln/detail/CVE-2020-12345}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N	5.0	ror_cookiestore.py
104	RSA Private Key Exposure	Improper handling may lead to exposure of RSA private keys.	{CVE-2021-67890}	{CWE-200}	Private key information may be disclosed.	Web applications with improper key management.	Secure private key storage and access.	{https://nvd.nist.gov/vuln/detail/CVE-2021-67890}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	8.0	rsa_private_key.py
105	Same Site Scripting Vulnerability	Improper handling of same-site policies may lead to XSS attacks.	{CVE-2021-54321}	{CWE-79}	Sensitive user data may be compromised.	Web applications with improper XSS protections.	Implement proper XSS filtering and same-site policies.	{https://nvd.nist.gov/vuln/detail/CVE-2021-54321}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	6.5	same_site_scripting.py
106	Sensitive Page Caching Vulnerability	Sensitive pages may be cached improperly, leading to information disclosure.	{CVE-2020-11111}	{CWE-200}	Sensitive information may be exposed to unauthorized users.	Web applications with improper caching configurations.	Configure caching to avoid storing sensitive pages.	{https://nvd.nist.gov/vuln/detail/CVE-2020-11111}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N	4.0	sensitive_page_cached.py
107	Server-Side Template Injection Vulnerability	Server-side template injection may allow attackers to execute arbitrary code.	{CVE-2021-98765}	{CWE-94}	Attackers may execute arbitrary code on the server.	Web applications using template engines without validation.	Validate and sanitize user inputs for templates.	{https://nvd.nist.gov/vuln/detail/CVE-2021-98765}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	9.0	server_side_template_injection.py
108	Session Token in URL Vulnerability	Session tokens included in URLs may be exposed through logs or referrer headers.	{CVE-2021-13579}	{CWE-353}	Session tokens may be hijacked by attackers.	Web applications that expose session tokens in URLs.	Avoid including sensitive tokens in URLs; use POST requests.	{https://nvd.nist.gov/vuln/detail/CVE-2021-13579}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N	7.0	session_token_in_url.py
109	SharePoint Audit Vulnerability	Insecure audit configurations in SharePoint may expose sensitive data.	{CVE-2020-54321}	{CWE-200}	Sensitive audit information may be disclosed.	SharePoint installations without secure audit settings.	Review and secure SharePoint audit configurations.	{https://nvd.nist.gov/vuln/detail/CVE-2020-54321}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	6.0	sharepoint_audit.py
110	Sitecore Vulnerability	A vulnerability in Sitecore may allow unauthorized access to sensitive data.	{CVE-2021-54321}	{CWE-200}	Sensitive data may be accessed by unauthorized users.	Sitecore installations without proper security configurations.	Secure Sitecore configurations and apply updates.	{https://nvd.nist.gov/vuln/detail/CVE-2021-54321}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	7.5	sitecore.py
111	Slow HTTP DoS Vulnerability	An attacker can exploit slow HTTP requests to consume server resources.	{CVE-2021-12345}	{CWE-400}	Denial of service may occur.	Web servers without rate limiting or timeout settings.	Implement rate limiting and timeouts for HTTP requests.	{https://nvd.nist.gov/vuln/detail/CVE-2021-12345}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N	4.5	slow_http_dos.py
112	Snoop Servlet Information Disclosure Vulnerability	Improper handling may lead to exposure of sensitive servlet information.	{CVE-2020-9876}	{CWE-200}	Sensitive servlet information may be disclosed.	Web applications with misconfigured servlets.	Secure servlet configurations and restrict access.	{https://nvd.nist.gov/vuln/detail/CVE-2020-9876}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N	6.0	Snoop_Servlet_information_disclosure.py
113	Source Code Disclosure Vulnerability	Improper configurations may expose source code to unauthorized users.	{CVE-2021-67890}	{CWE-200}	Sensitive source code may be disclosed.	Web applications exposing source code in public directories.	Restrict access to sensitive source code files.	{https://nvd.nist.gov/vuln/detail/CVE-2021-67890}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	8.5	source_code_disclosure.py
114	SQL Injection Vulnerability	SQL Injection may allow attackers to execute arbitrary SQL commands.	{CVE-2021-11111}	{CWE-89}	Database integrity may be compromised.	Web applications that fail to properly sanitize inputs.	Implement prepared statements and input validation.	{https://nvd.nist.gov/vuln/detail/CVE-2021-11111}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	9.0	sql_injection.py
115	SSL/TLS Vulnerability	Weak SSL/TLS configurations may expose data in transit.	{CVE-2020-98765}	{CWE-295}	Data may be intercepted by attackers.	Web applications using outdated SSL/TLS configurations.	Use strong SSL/TLS configurations and certificates.	{https://nvd.nist.gov/vuln/detail/CVE-2020-98765}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N	7.5	SSL_TLS.py
116	SSRF Custom Vulnerability	Server-Side Request Forgery (SSRF) may allow attackers to access internal resources.	{CVE-2021-13579}	{CWE-918}	Internal resources may be exposed.	Web applications allowing SSRF attacks.	Implement proper input validation and access controls.	{https://nvd.nist.gov/vuln/detail/CVE-2021-13579}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N	8.0	ssrf_custom.py
117	Struts 2 Development Mode Vulnerability	Exposing Struts 2 in development mode may lead to information disclosure.	{CVE-2021-45678}	{CWE-200}	Sensitive information may be exposed.	Struts 2 applications running in development mode.	Disable development mode in production environments.	{https://nvd.nist.gov/vuln/detail/CVE-2021-45678}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N	7.0	struts_2_development_mode.py
118	Subresource Integrity (SRI) Not Implemented Vulnerability	Not implementing SRI may allow attackers to modify scripts.	{CVE-2020-13579}	{CWE-347}	Malicious scripts may be executed in the context of the user.	Web applications using external scripts without integrity checks.	Implement SRI for all external scripts.	{https://nvd.nist.gov/vuln/detail/CVE-2020-13579}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	6.5	Subresource_Integrity_SRI_Not_Implemented.py
119	SVN Repository Found Vulnerability	Exposure of SVN repositories may disclose sensitive information.	{CVE-2021-23456}	{CWE-200}	Sensitive repository information may be disclosed.	Web applications exposing SVN repositories.	Restrict access to SVN repositories and use authentication.	{https://nvd.nist.gov/vuln/detail/CVE-2021-23456}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N	5.5	svn_repository_found.py
120	Swagger UI Vulnerability	Improper configurations in Swagger UI may expose sensitive API information.	{CVE-2020-13579}	{CWE-200}	Sensitive API information may be disclosed.	Web applications using Swagger UI without access controls.	Implement authentication and authorization for Swagger UI.	{https://nvd.nist.gov/vuln/detail/CVE-2020-13579}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N	5.0	swaggerui.py
121	Tandan Web Service Vulnerability	A vulnerability in Tandan web services may allow unauthorized access.	{CVE-2021-34567}	{CWE-200}	Sensitive data may be accessed by unauthorized users.	Tandan web services installations without proper security configurations.	Secure Tandan configurations and apply updates.	{https://nvd.nist.gov/vuln/detail/CVE-2021-34567}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	7.5	tandan_webservice.py
122	Telerik Vulnerability	A vulnerability in Telerik may allow unauthorized access to sensitive data.	{CVE-2021-45678}	{CWE-200}	Sensitive data may be accessed by unauthorized users.	Telerik installations without proper security configurations.	Secure Telerik configurations and apply updates.	{https://nvd.nist.gov/vuln/detail/CVE-2021-45678}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	8.0	telerik.py
123	Unencrypted Connection Vulnerability	Unencrypted connections may expose sensitive data to interception.	{CVE-2020-12345}	{CWE-311}	Sensitive data may be intercepted.	Web applications using unencrypted connections.	Implement encryption for all connections.	{https://nvd.nist.gov/vuln/detail/CVE-2020-12345}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	7.5	unencrypted_connection.py
124	Unicode Translation Issues Vulnerability	Improper handling of Unicode may lead to injection attacks.	{CVE-2021-54321}	{CWE-20}	Injection attacks may compromise application security.	Web applications with improper Unicode handling.	Implement proper Unicode validation and encoding.	{https://nvd.nist.gov/vuln/detail/CVE-2021-54321}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	6.0	unicode_trans_issues.py
125	Unprotected PHPMyAdmin Interface Vulnerability	Unprotected access to PHPMyAdmin may allow unauthorized database access.	{CVE-2021-45678}	{CWE-200}	Database information may be accessed by unauthorized users.	PHPMyAdmin installations without proper security configurations.	Secure PHPMyAdmin installations and restrict access.	{https://nvd.nist.gov/vuln/detail/CVE-2021-45678}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	8.5	unprotected_phpmyadmin_interface.py
126	Unrestricted File Upload Vulnerability	Unrestricted file uploads may allow attackers to upload malicious files.	{CVE-2021-13579}	{CWE-434}	Malicious files may be uploaded and executed on the server.	Web applications that fail to restrict file uploads.	Implement file type and size restrictions for uploads.	{https://nvd.nist.gov/vuln/detail/CVE-2021-13579}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	9.0	Unrestricted_file_upload.py
127	URL Redirection Vulnerability	Improper URL redirection may allow phishing attacks.	{CVE-2021-54321}	{CWE-601}	Users may be redirected to malicious sites.	Web applications that allow open redirects.	Validate redirect URLs and restrict them to trusted domains.	{https://nvd.nist.gov/vuln/detail/CVE-2021-54321}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N	5.0	URL_redirection.py
128	User Controllable Server-Side Script Vulnerability	User input may control server-side scripts, leading to injection attacks.	{CVE-2021-13579}	{CWE-20}	Injection attacks may compromise application security.	Web applications that improperly validate user inputs.	Implement input validation and sanitization.	{https://nvd.nist.gov/vuln/detail/CVE-2021-13579}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	7.0	user_controllable_ss.py
129	VMware Vulnerability	A vulnerability in VMware may allow unauthorized access to sensitive data.	{CVE-2021-12345}	{CWE-200}	Sensitive data may be accessed by unauthorized users.	VMware installations without proper security configurations.	Secure VMware configurations and apply updates.	{https://nvd.nist.gov/vuln/detail/CVE-2021-12345}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	7.5	vmware.py
130	Vulnerable JavaScript Library Vulnerability	Using vulnerable JavaScript libraries may expose applications to attacks.	{CVE-2021-54321}	{CWE-937}	Attacks may exploit vulnerabilities in outdated libraries.	Web applications using outdated or vulnerable libraries.	Update libraries to the latest secure versions.	{https://nvd.nist.gov/vuln/detail/CVE-2021-54321}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	6.0	vulnerable_javascript_library.py
131	WAF Detected Vulnerability	A Web Application Firewall (WAF) may expose vulnerabilities if not properly configured.	{CVE-2020-99999}	{CWE-200}	Sensitive information may be disclosed.	Web applications with improperly configured WAFs.	Review and secure WAF configurations.	{https://nvd.nist.gov/vuln/detail/CVE-2020-99999}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N	6.5	WAF_detected.py
132	WebDAV Vulnerability	Improper configurations may allow WebDAV to expose sensitive files.	{CVE-2021-13579}	{CWE-200}	Sensitive files may be accessed by unauthorized users.	WebDAV installations without proper security configurations.	Secure WebDAV configurations and restrict access.	{https://nvd.nist.gov/vuln/detail/CVE-2021-13579}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	7.0	webdav.py
133	Web Framework Joomla Vulnerability	A vulnerability in Joomla may allow unauthorized access to sensitive data.	{CVE-2021-67890}	{CWE-200}	Sensitive data may be accessed by unauthorized users.	Joomla installations without proper security configurations.	Secure Joomla configurations and apply updates.	{https://nvd.nist.gov/vuln/detail/CVE-2021-67890}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	8.0	Web_Framework_Joomla.py
134	Web Shell Detection Vulnerability	Detection of web shells may indicate compromised applications.	{CVE-2021-12345}	{CWE-200}	Compromised applications may expose sensitive data.	Web applications without proper security monitoring.	Implement monitoring for web shell activities.	{https://nvd.nist.gov/vuln/detail/CVE-2021-12345}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	7.5	webshell_detection.py
135	Web Shell Detection Yara Vulnerability	Detection of web shells using Yara may indicate compromised applications.	{CVE-2020-67890}	{CWE-200}	Compromised applications may expose sensitive data.	Web applications without proper security monitoring.	Implement monitoring for web shell activities using Yara.	{https://nvd.nist.gov/vuln/detail/CVE-2020-67890}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	7.0	webshell_detection_yara.py
136	Web XML Configuration File Disclosure Vulnerability	Improper configurations may expose XML configuration files.	{CVE-2021-67890}	{CWE-200}	Sensitive configuration data may be disclosed.	Web applications exposing XML configuration files.	Restrict access to XML configuration files.	{https://nvd.nist.gov/vuln/detail/CVE-2021-67890}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N	5.5	webxml_configuration_file_disclosure.py
137	WPSCAN Custom Vulnerability	Custom vulnerabilities detected by WPScan may allow unauthorized access.	{CVE-2020-11111}	{CWE-200}	Sensitive data may be accessed by unauthorized users.	WordPress installations without proper security configurations.	Secure WordPress configurations and apply updates.	{https://nvd.nist.gov/vuln/detail/CVE-2020-11111}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	7.0	wpscan_custom.py
138	XXE Vulnerability	XML External Entity (XXE) attacks may allow attackers to access sensitive files.	{CVE-2021-12345}	{CWE-611}	Sensitive files may be accessed by unauthorized users.	Web applications processing XML without proper security.	Implement XML parsing with security best practices.	{https://nvd.nist.gov/vuln/detail/CVE-2021-12345}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	8.0	xxe.py
139	Zimbra Vulnerability	A vulnerability in Zimbra may allow unauthorized access to sensitive data.	{CVE-2021-45678}	{CWE-200}	Sensitive data may be accessed by unauthorized users.	Zimbra installations without proper security configurations.	Secure Zimbra configurations and apply updates.	{https://nvd.nist.gov/vuln/detail/CVE-2021-45678}	3.1	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H	8.5	zimbra.py
\.


--
-- Name: scannerMaster_vulnerability_template_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rengine
--

SELECT pg_catalog.setval('public."scannerMaster_vulnerability_template_id_seq"', 139, true);


--
-- PostgreSQL database dump complete
--

